version: "3.8"

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    container_name: nangman-note-api-gateway
    ports:
      - "3000:3000"
    env_file: .env

  note-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: note-service
    container_name: nangman-note-note-service
    ports:
      - "3001:3001"
    env_file: .env

  meeting-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: meeting-service
    container_name: nangman-note-meeting-service
    ports:
      - "3002:3002"
    env_file: .env

  ai-processing-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: ai-processing-service
    container_name: nangman-note-ai-processing-service
    ports:
      - "3003:3003"
    env_file: .env

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: nangman-note-frontend
    ports:
      - "3004:3000"
    env_file: .env
